package hu.xannosz.flyingships.screen.widget;

public enum ButtonId {
	//main buttons
	UP,
	DOWN,
	RIGHT,
	LEFT,
	FORWARD,
	BACKWARD,
	LAND,
	POWER,

	INCREASE,
	DECREASE,
	PLUS,
	MINUS,

	MENU,
	JUMP,
	BEACON,
	DIMENSION,

	//settings buttons
	BLOCK_POS_EDITION_DOWN,
	RECTANGLE_PAGE_UP,
	RECTANGLE_PAGE_DOWN,
	ADD_NEW_RECTANGLE,
	BACK,

	EDIT_REC_1,
	DELETE_REC_1,
	EDIT_REC_2,
	DELETE_REC_2,
	EDIT_REC_3,
	DELETE_REC_3,

	OK_EDITION,
	EXIT_EDITION,

	WATER_LINE_UP,
	WATER_LINE_DOWN,

	// coordinates

	COORDINATE_PAGE_UP,
	COORDINATE_PAGE_DOWN,
	ADD_NEW_COORDINATE,

	JUMP_TO_COORDINATE_1,
	EDIT_COORDINATE_1,
	JUMP_TO_COORDINATE_2,
	EDIT_COORDINATE_2,
	JUMP_TO_COORDINATE_3,
	EDIT_COORDINATE_3,
	JUMP_TO_COORDINATE_4,
	EDIT_COORDINATE_4,
	JUMP_TO_COORDINATE_5,
	EDIT_COORDINATE_5,
	JUMP_TO_COORDINATE_6,
	EDIT_COORDINATE_6,

	ADD_COORDINATE,
	EXIT_COORDINATE_EDITION,
	DELETE_COORDINATE,
	MARKER_UP,
	MARKER_DOWN,
	ABSOLUTE_COORDINATE,
	EDITION_COORDINATE_DONE,

	MARKER_NAME_EDITION_DONE,
	MARKER_SET_ENABLED,

	ENDER_ENGINE,
	STEAM_ENGINE,
	HEAT_ENGINE,

	NEXT_INNER_ROUND,

	// rune
	RUNE_GO_UP,
	RUNE_GO_Y_P,
	RUNE_GO_Z_M,

	RUNE_GO_X_M,
	RUNE_GO_NEAR,
	RUNE_GO_X_P,

	RUNE_GO_Z_P,
	RUNE_GO_Y_M,
	RUNE_GO_DOWN,

	RUNE_SWITCH_WAND,
	RUNE_OK,
	RUNE_SWITCH_REDSTONE
}
